### PR TITLE
WIP: V2 build

### PR DESCRIPTION
**Pull request by georgyangelov**
I started configuring the build environment for V2 as we decided to use SCSS.

TODO:

- [X] Add SCSS
- [X] Add automatic `!important` suffixes on build
- [X] Add SCSS linter
- [x] Write some setup and contribution guides in the README
- [x] Add the `manifest.json` to the build
- [x] Check for any new versions of `manifest.json` and new helpful options
- [x] Set up the button for the style switching
- [x] Set up Travis for PR and lint checking
- [x] Specify some base variables and mixins for the design
- [x] Automate ZIP file creation for upload to the Chrome Web Store (zipping only the necessary files)

/cc @Dancanplay @NSDex what do you think? You are free to push to this branch if you want :)

EDIT: Yes, I changed my github username :)

### CODE REVIEW

**Comment by NSDex** [comment]
What is the difference between v2 and v2-build ?

**Comment by Dancanplay** [comment]
v2-build will be merged to v2, I guess.

**Comment by georgyangelov** [comment]
Yes, I wanted to not show the giant diff for the removal of `dark.css` and made a clear base branch. The idea is to use `v2` once this is merged

**Comment by georgyangelov** [comment]
Everything should be set up now :) I did some super-quick styling:

screen shot 2016-10-09 at 01 12 06
screen shot 2016-10-09 at 01 17 10
screen shot 2016-10-09 at 01 17 21

**Comment by georgyangelov** [comment]
Looks like they are using a front-end framework now and so there are semantic tags that are easier to target (such as `<iron-icon>` and `<yt-formatted-string>`) :)

**Comment by georgyangelov** [comment]
Added CI lint and zip task.

Do you have any comments on these changes - the build, scss, structure, etc.? I'd like to merge this so we can add the styles in the `v2` branch once Youtube switches to the new design for all users.

**Comment by Dancanplay** [comment]
Maybe a switch between legacy and the new CSS, people may like to stay on the old design.

**Comment by georgyangelov** [comment]
People will most definitely want to stay on the old design, just human nature. But Youtube will change it and people will not have a choice :)

**Comment by georgyangelov** [comment]
I'm merging this. We can push style updates in the `v2` branch

**Pull request merged**
